version: "3"

services:
  nuxt:
    build: "."
    container_name: "nuxt-app"
    working_dir: "/usr/src/app"
    ports:
    - "3000:3000"
    volumes:
    - "$PWD:/usr/src/app/"
    - "node_modules:/usr/src/app/node_modules"
    command: "npx nuxt-ts"

volumes:
  node_modules:
